### ISSUE TITLE
Fix crash in Linux due to using iconbitmap to set the window icon 

### ISSUE THREAD

**Issue by alexpalade** [polynoman/Game-of-Life-Simulator#28]
The function `Tkinter.Tk.iconbitmap` that sets the window icon doesn't work on Linux. It crashes with all the image formats I've tried except XBM, which runs on Linux, but doesn't set the icon and on Windows it looks bad because it's monochrome.

https://github.com/polynoman/Game-of-Life-Simulator/blob/508bc5697ec43e2044b1b8d23d5c2feb7fbeac2d/src/gui.py#L25

<details>
<summary>Traceback details</summary>

```
$ python game.py
Traceback (most recent call last):
  File "/tmp/Game-of-Life-Simulator/src/game.py", line 108, in <module>
    game = gameOfLife(gameMatrix)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/Game-of-Life-Simulator/src/game.py", line 31, in __init__
    self.setupGui()
  File "/tmp/Game-of-Life-Simulator/src/game.py", line 98, in setupGui
    self.app = gui.App(game=self)
               ^^^^^^^^^^^^^^^^^^
  File "/tmp/Game-of-Life-Simulator/src/gui.py", line 32, in __init__
    self.iconbitmap("../media/icon/gol_64.ico")
  File "/usr/lib/python3.11/tkinter/__init__.py", line 2136, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: bitmap "../media/icon/gol_64.ico" not defined
```
</details>

The issue is with the `iconbitmap` function. The image path is correct: `os.path.isfile("../media/icon/gol_64.ico")` returns `True`.

I suggest using the `iconphoto` method instead, which worked both on Windows and Linux. It can use the PNG image format and the other formats supported by Tkinter. It came up as a solution on Stackoverflow, etc.

I'll submit a PR with this particular fix, but feel free to close that PR if you'd don't want it / prefer another solution.

**Comment by polynoman** [comment]
Hi alexpalade, thank you for your contribution. Very much appreciated!
